baseURL = 'https://example.org/'
title = 'RickyTech-Journal'
theme = 'PaperMod'

defaultContentLanguage = 'en'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[minify]
disableXML = true
minifyOutput = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[taxonomies]
tag = "tags"
category = "categories"

[markup.highlight]
noClasses = false

[params]
env = "production"
title = "ExampleSite"
description = "ExampleSite description"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Me"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Home"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = false
  title = "ExampleSite"
  subtitle = "This is subtitle"
  imageUrl = "<img location>"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hi there 👋"
  Content = "Welcome to Ricky Tech Journal"

  [[params.socialIcons]]
  name = "x"
  url = "https://x.com/_nxttrung0312"

  [[params.socialIcons]]
  name = "facebook"
  url = "https://www.facebook.com/tuantrung.nguyenxuan"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/nguyen-xuan-tuan-trung-564362186/"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/Tuantrung"

  [params.analytics.google]
  SiteVerificationTag = "XYZabc"

  [params.analytics.bing]
  SiteVerificationTag = "XYZabc"

  [params.analytics.yandex]
  SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/<path_to_repo>/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  limit = 10
  keys = [ "title", "permalink", "summary", "content" ]

[languages]

  [languages.en]
  languageName = "English"
  languageCode = "en-us"
  weight = 1
  title = "RickyTech-Journal"

    [[languages.en.menu.main]]
    identifier = "Archives"
    name = "Archives"
    url = "/archives/"
    weight = 10

    [[languages.en.menu.main]]
    identifier = "Topics"
    name = "Topics"
    url = "/tags/"
    weight = 20

    [[languages.en.menu.main]]
    identifier = "Search"
    name = "Search"
    url = "/search/"
    weight = 30

  [languages.vi]
  languageName = "Tiếng Việt"
  languageCode = "vi"
  weight = 2
  title = "RickyTech-Journal"

    [languages.vi.params.homeInfoParams]
    Title = "Xin chào 👋"
    Content = "Chào mừng đến với Ricky Tech Journal"

    [[languages.vi.menu.main]]
    identifier = "Archives"
    name = "Lưu trữ"
    url = "/vi/archives/"
    weight = 10

    [[languages.vi.menu.main]]
    identifier = "Topics"
    name = "Chủ đề"
    url = "/vi/tags/"
    weight = 20

    [[languages.vi.menu.main]]
    identifier = "Search"
    name = "Tìm kiếm"
    url = "/vi/search/"
    weight = 30
